FROM python:3.12-slim

WORKDIR /usr/app

COPY Performance /usr/app/Performance

RUN python -m pip install --no-cache-dir -r /usr/app/Performance/Python/REST/FastAPI/requirements.txt

EXPOSE 5200

CMD ["python", "-m", "uvicorn", "Performance.Python.REST.FastAPI.server:app", "--host", "0.0.0.0", "--port", "5200"]
